exameer/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'exameer.views.home', name='home'),
    # url(r'^exameer/', include('exameer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^course/', include('examer.urls', namespace='examer')),
)

examer/urls.py
from django.conf.urls import patterns, include, url

from examer import views

urlpatterns = patterns('',
                       url(r'^all/$', views.IndexView.as_view(), name='index'),
                       url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
                       url(r'^(?P<pk>\d+)/random/random/$', views.RandomQuestionFromCourseView, name='random_question'),
                       url(r'^(?P<course_id>\d+)/(?P<exam_id>\d+)/(?P<question_id>\d+)/$', views.ShowQuestionView,
                           name='question'),
                       )

examer/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Exam(models.Model):
    course = models.ForeignKey(Course)

    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class ExamQuestion(models.Model):
    exam = models.ForeignKey(Exam)
    name = models.IntegerField()

    def __unicode__(self):
        return str(self.name)


class Tag(models.Model):
    question = models.ForeignKey(ExamQuestion)
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return str(self.name)

examer/views.py
# Create your views here.
from random import randint
from django.shortcuts import get_object_or_404, render
from django.views import generic
from examer.models import Course, Exam, ExamQuestion


class IndexView(generic.ListView):
    template_name = 'examer/index.html'
    context_object_name = 'courses'

    def get_queryset(self):
        """Return all courses"""
        return Course.objects.all()


class DetailView(generic.DetailView):
    model = Course
    template_name = 'examer/detail.html'

    def get_queryset(self):
        """Return all exams for this course"""
        return super(DetailView, self).get_queryset().filter(id=self.kwargs['pk'])


def RandomQuestionFromCourseView(request, pk):
    course = get_object_or_404(Course, pk=pk)
    exam = course.exam_set.filter(course_id=pk).order_by('?')[0]
    question = exam.examquestion_set.filter(exam_id=exam.id).order_by('?')[0]

    return render(request, 'examer/question.html', {'course': course, 'exam': exam, 'question': question})


def ShowQuestionView(request, course_id, exam_id, question_id):
    question = get_object_or_404(ExamQuestion, pk=question_id)
    exam = question.exam
    print exam.name
    course = exam.course

    return render(request, 'examer/question.html', {'course': course, 'exam': exam, 'question': question})

examer/templates/examer/course_list.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
asdasd
</body>
</html>

examer/templates/examer/detail.html
<h1>{{ course.name }}</h1>
<p>{{ course.description }}</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<a href="{% url 'examer:index' %}">>> Courses</a>

examer/templates/examer/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'examer/style.css' %}"/>

{% if courses %}
    <ul>
        {% for course in courses %}
            <li>
                <a href="{% url 'examer:detail' course.id %}">{{ course.name }}</a>
                {% comment %}<ul>
                    {% for exam in course.exam_set.all %}
                        {% for question in exam.examquestion_set.all %}
                            <li><img class="answer" src="{{ STATIC_URL }}examer/images/courses/{{ course.name }}/exams/{{ exam.name }}/{{ question.name }}.png" /></li>
                            <li><img class="solution" src="{{ STATIC_URL }}examer/images/courses/{{ course.name }}/solutions/{{ exam.name }}/{{ question.name }}.png" /></li>
                        {% endfor %}
                    {% endfor %}
                </ul>{% endcomment %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No courses are available.</p>
{% endif %}

examer/templates/examer/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'examer/assets/ico/favicon.png' %}">

    <title>Exameer</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'examer/dist/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'examer/jumbotron.css' %}" rel="stylesheet">

    {% block header %} {% endblock %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'examer/assets/js/html5shiv.js' %}"></script>
      <script src="{% static 'examer/assets/js/respond.min.js' %}"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Exameer</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">


                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
{#            <form class="navbar-form navbar-right">#}
{#                <div class="form-group">#}
{#                    <input type="text" placeholder="Email" class="form-control">#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <input type="password" placeholder="Password" class="form-control">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-success">Sign in</button>#}
{#            </form>#}
        </div>
        <!--/.navbar-collapse -->
    </div>
</div>

<div class="container">
    {% block content %}

    <!-- Example row of columns -->
    <div class="row">
        <div class="col-lg-4">
            <h2>Heading</h2>

            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis
                euismod. Donec sed odio dui. </p>

            <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2>Heading</h2>

            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis
                euismod. Donec sed odio dui. </p>

            <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2>Heading</h2>

            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula
                porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus.</p>

            <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
        </div>
    </div>

    {% endblock %}

    <hr>

    <footer>
        <p>&copy; Company 2013</p>
    </footer>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'examer/assets/js/jquery.js' %}"></script>
<script src="{% static 'examer/dist/js/bootstrap.min.js' %}"></script>
{% block footer %}
{% endblock %}
</body>
</html>

examer/templates/examer/question.html
{% extends "examer/master.html" %}

{% load staticfiles %}

{% block footer %}
    <link rel="stylesheet" type="text/css" href="{% static 'examer/style.css' %}"/>
    <script src="{% static 'examer/custom.js' %}"></script>
{% endblock footer %}

{% block content %}
    <a href="{% url 'examer:question' course.id exam.id question.id %}">Permanent link</a> --
    <a href="/course/{{ course.id }}/{{ exam.id }}/{{ question.id|add:-1 }}">Prev</a> -
    <a href="{% url 'examer:random_question' course.id %}">Random</a> -
    <a href="/course/{{ course.id }}/{{ exam.id }}/{{ question.id|add:1 }}">Next</a>

    <div class="row">

        <h1>{{ course.name }}/{{ course.id }}/{{ exam.id }}/{{ question.id }}</h1>

        <p>{{ course.description }}</p>
    </div>
    <br/>

    <div class="row">

            <img class="answer"
                 src="{{ STATIC_URL }}examer/images/courses/{{ course.name }}/exams/{{ exam.name }}/{{ question.name }}.png"/>


            <div class="solution_box">
                <img class="solution"
                     src="{{ STATIC_URL }}examer/images/courses/{{ course.name }}/solutions/{{ exam.name }}/{{ question.name }}.png"/>
            </div>

   </div>
{% endblock content %}